# Creates (or refreshes) a Desktop shortcut that launches mapgen
# windowless: no console window, and the server stops itself once the
# page is closed (see `mapgen ui --windowless` / mapgen.web.server's
# heartbeat watchdog). `mapgen ui` typed directly into a terminal is
# completely unaffected by any of this: this script only changes how the
# SHORTCUT launches, never the command itself.
#
# Safe to re-run at any time: CreateShortcut/.Save() overwrite an existing
# shortcut at the same path cleanly, so moving the repo, rebuilding the
# icon, or just wanting a fresh copy is a matter of running this again
# rather than deleting anything by hand first. This is deliberate: a
# shortcut generated by a committed script is reproducible, a hand-edited
# .lnk is not.
$ErrorActionPreference = "Stop"
$assetsDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$root = Split-Path -Parent $assetsDir

# pythonw.exe, not python.exe: the standard, dependency-free way to run a
# Python script with no console window at all. It ships alongside
# python.exe in every venv `python -m venv` creates, so nothing further
# needs installing for this specifically. `-m mapgen` rather than a
# packaged console_scripts/gui_scripts entry point, so this script needs
# no pyproject.toml changes and works against a venv that has already
# been bootstrap.ps1'd without a re-install.
$pythonw = Join-Path $root ".venv\Scripts\pythonw.exe"
if (-not (Test-Path $pythonw)) {
    Write-Error "pythonw.exe not found at $pythonw`nRun bootstrap.ps1 first to create the virtual environment."
}

# A real, if partial, check that mapgen is actually importable from this
# venv, not just that a venv exists: bootstrap.ps1 installs mapgen in
# editable mode, which is also what puts mapgen.exe on .venv\Scripts.
# pythonw.exe alone proves nothing beyond "a venv was created".
$mapgenConsoleScript = Join-Path $root ".venv\Scripts\mapgen.exe"
if (-not (Test-Path $mapgenConsoleScript)) {
    Write-Error "mapgen is not installed in $root\.venv`nRun bootstrap.ps1 first (or re-run it if the venv predates it)."
}

$icon = Join-Path $assetsDir "mapgen.ico"
if (-not (Test-Path $icon)) {
    Write-Error "Icon not found at $icon`nRegenerate it with: .venv\Scripts\python.exe assets\make_icon.py assets\mapgen.ico"
}

$desktop = [Environment]::GetFolderPath("Desktop")
$shortcutPath = Join-Path $desktop "mapgen.lnk"

$shell = New-Object -ComObject WScript.Shell
$shortcut = $shell.CreateShortcut($shortcutPath)
$shortcut.TargetPath = $pythonw
$shortcut.Arguments = "-m mapgen ui --windowless"
$shortcut.WorkingDirectory = $root
$shortcut.IconLocation = $icon
$shortcut.Description = "mapgen: site survey data for architectural work"
$shortcut.Save()

Write-Host "Shortcut created: $shortcutPath"
Write-Host "  Target:      $pythonw"
Write-Host "  Arguments:   -m mapgen ui --windowless"
Write-Host "  Working dir: $root"
Write-Host ""
Write-Host "No console window will appear. If it fails to start, or the page never"
Write-Host "opens, check the log at:"
Write-Host "  $env:USERPROFILE\.mapgen\ui.log"
Write-Host "A message box will also appear on a failure that stops the server before"
Write-Host "it can even open the page."
